export const extractDialogues = (prompt: string): string[] => {
  const dialogues: string[] = Array(10).fill("");
  for (let i = 1; i <= 10; i++) {
    const pRegex = new RegExp(`(?:P|Panel)\\s*${i}[:\\s](.*?)(?=(?:P|Panel)\\s*${i+1}[:\\s]|$)`, 'is');
    const pMatch = prompt.match(pRegex);
    if (pMatch) {
      const pText = pMatch[1];
      const dMatch = pText.match(/\|\s*Dialogue:\s*"([^"]+)"/i) || pText.match(/\|\s*Dialogue:\s*([^|]+)/i);
      if (dMatch) {
        dialogues[i-1] = dMatch[1].replace(/["']/g, '').trim();
      }
    }
  }
  return dialogues;
};

export const drawImageWithText = async (base64Image: string, prompt: string, layout: '2x2' | '2x1' | '3x1' | '3x3'): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        resolve(base64Image);
        return;
      }
      ctx.drawImage(img, 0, 0);

      const dialogues = extractDialogues(prompt);
      const cols = layout === '3x3' ? 3 : (layout === '2x2' ? 2 : (layout === '3x1' ? 3 : 2));
      const rows = layout === '3x3' ? 3 : (layout === '2x2' ? 2 : 1);
      const panelWidth = canvas.width / cols;
      const panelHeight = canvas.height / rows;

      // Draw thick black grid lines to cover any white space generated by the AI
      ctx.strokeStyle = 'black';
      ctx.lineWidth = 12; // Thick enough to cover most white space
      
      // Draw vertical lines
      for (let i = 1; i < cols; i++) {
        ctx.beginPath();
        ctx.moveTo(i * panelWidth, 0);
        ctx.lineTo(i * panelWidth, canvas.height);
        ctx.stroke();
      }
      
      // Draw horizontal lines
      for (let i = 1; i < rows; i++) {
        ctx.beginPath();
        ctx.moveTo(0, i * panelHeight);
        ctx.lineTo(canvas.width, i * panelHeight);
        ctx.stroke();
      }
      
      // Draw outer border to cover outer white space
      ctx.lineWidth = 24;
      ctx.strokeRect(0, 0, canvas.width, canvas.height);

      dialogues.forEach((text, idx) => {
        if (!text) return;
        const col = idx % cols;
        const row = Math.floor(idx / cols);
        
        const padding = panelWidth * 0.05;
        const maxWidth = panelWidth - padding * 2;
        
        const fontSize = Math.max(28, Math.floor(panelHeight * 0.12));
        ctx.font = `bold ${fontSize}px "Comic Sans MS", "Arial", sans-serif`;
        ctx.textBaseline = 'top';
        ctx.textAlign = 'center';

        const words = text.split(' ');
        let line = '';
        const lines: string[] = [];
        for (let n = 0; n < words.length; n++) {
          const testLine = line + words[n] + ' ';
          const metrics = ctx.measureText(testLine);
          if (metrics.width > maxWidth && n > 0) {
            lines.push(line);
            line = words[n] + ' ';
          } else {
            line = testLine;
          }
        }
        lines.push(line);

        const lineHeight = fontSize * 1.2;
        const textHeight = lines.length * lineHeight;
        
        const boxPadding = Math.max(16, fontSize * 0.6);
        const boxWidth = Math.min(maxWidth, Math.max(...lines.map(l => ctx.measureText(l).width)) + boxPadding);
        const boxHeight = textHeight + boxPadding;
        
        const x = col * panelWidth + panelWidth / 2;
        const y = row * panelHeight + panelHeight - boxHeight;

        ctx.fillStyle = 'white';
        ctx.strokeStyle = 'black';
        ctx.lineWidth = Math.max(2, Math.floor(fontSize * 0.1));
        
        const r = 8;
        const bx = x - boxWidth / 2;
        const by = y;
        ctx.beginPath();
        ctx.moveTo(bx + r, by);
        ctx.lineTo(bx + boxWidth - r, by);
        ctx.quadraticCurveTo(bx + boxWidth, by, bx + boxWidth, by + r);
        ctx.lineTo(bx + boxWidth, by + boxHeight - r);
        ctx.quadraticCurveTo(bx + boxWidth, by + boxHeight, bx + boxWidth - r, by + boxHeight);
        ctx.lineTo(bx + r, by + boxHeight);
        ctx.quadraticCurveTo(bx, by + boxHeight, bx, by + boxHeight - r);
        ctx.lineTo(bx, by + r);
        ctx.quadraticCurveTo(bx, by, bx + r, by);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();

        ctx.fillStyle = 'black';
        lines.forEach((l, i) => {
          ctx.fillText(l.trim(), x, y + (boxPadding / 2) + i * lineHeight);
        });
      });

      resolve(canvas.toDataURL('image/png').split(',')[1]);
    };
    img.onerror = () => resolve(base64Image);
    img.src = `data:image/png;base64,${base64Image}`;
  });
};
